version: "3"
 
services:
  tomcat:
    image: tomcat:9.0.76-jre11-temurin
    restart: no
    ports:
      - "8081:8080"
        #command: "/bin/bash"
    volumes:
      - ./ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    links:
      - mysql
  mysql:
    image: mysql            
    restart: always        
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:            
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jjh
      MYSQL_USER: jjh
      MYSQL_PASSWORD: jsppw
    ports:      
      - '3306:3306'
